title: Mathular
description: Mathular is a website which aims to provide both theoretical and visual content for mathematics.
url: "https://mathular.com" # base hostname of the website
github_username: ShivamVashishtha

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
